# Generated by Django 4.0.3 on 2022-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_name_category_categoryname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='manufucturer',
            field=models.CharField(default='Unidentified', max_length=200),
        ),
    ]
