# Generated by Django 4.0.3 on 2022-04-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sales_product_manufucturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
